-- MySQL Script generated by MySQL Workbench
-- Tue 31 Mar 2020 03:06:18 PM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wow_classic_assistant
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wow_classic_assistant
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wow_classic_assistant` DEFAULT CHARACTER SET utf8 ;
USE `wow_classic_assistant` ;

-- -----------------------------------------------------
-- Table `wow_classic_assistant`.`craftable_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wow_classic_assistant`.`craftable_item` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `item_link_url` VARCHAR(255) NOT NULL,
  `icon_link_url` VARCHAR(255) NOT NULL,
  `item_slot` VARCHAR(255) NOT NULL DEFAULT 'Not equipable',
  `sell_price` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `item_link_url_UNIQUE` (`item_link_url` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wow_classic_assistant`.`reagent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wow_classic_assistant`.`reagent` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `item_link_url` VARCHAR(255) NOT NULL,
  `icon_link_url` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `item_link_url_UNIQUE` (`item_link_url` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wow_classic_assistant`.`profession`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wow_classic_assistant`.`profession` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `profession_link_url` VARCHAR(255) NOT NULL,
  `icon_link_url` VARCHAR(255) NOT NULL,
  `is_main_profession` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `profession_link_url_UNIQUE` (`profession_link_url` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wow_classic_assistant`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wow_classic_assistant`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wow_classic_assistant`.`faction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wow_classic_assistant`.`faction` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wow_classic_assistant`.`playable_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wow_classic_assistant`.`playable_class` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wow_classic_assistant`.`character`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wow_classic_assistant`.`character` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `faction_id` INT UNSIGNED NOT NULL,
  `playable_class_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_character_user1_idx` (`user_id` ASC),
  INDEX `fk_character_factions1_idx` (`faction_id` ASC),
  INDEX `fk_character_playable_classes1_idx` (`playable_class_id` ASC),
  CONSTRAINT `fk_character_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `wow_classic_assistant`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_character_factions1`
    FOREIGN KEY (`faction_id`)
    REFERENCES `wow_classic_assistant`.`faction` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_character_playable_classes1`
    FOREIGN KEY (`playable_class_id`)
    REFERENCES `wow_classic_assistant`.`playable_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wow_classic_assistant`.`recipe_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wow_classic_assistant`.`recipe_item` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `item_link_url` VARCHAR(255) NOT NULL,
  `icon_link_url` VARCHAR(255) NOT NULL,
  `required_skill_level` INT UNSIGNED NOT NULL DEFAULT 1,
  `profession_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_recipe_item_profession1_idx` (`profession_id` ASC),
  UNIQUE INDEX `item_link_url_UNIQUE` (`item_link_url` ASC),
  CONSTRAINT `fk_recipe_item_profession1`
    FOREIGN KEY (`profession_id`)
    REFERENCES `wow_classic_assistant`.`profession` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wow_classic_assistant`.`recipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wow_classic_assistant`.`recipe` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `difficulty_requirement` INT UNSIGNED NOT NULL DEFAULT 1,
  `difficulty_category_1` INT UNSIGNED NOT NULL DEFAULT 1,
  `difficulty_category_2` INT UNSIGNED NOT NULL DEFAULT 1,
  `difficulty_category_3` INT UNSIGNED NOT NULL DEFAULT 1,
  `difficulty_category_4` INT UNSIGNED NOT NULL DEFAULT 1,
  `recipe_link_url` VARCHAR(255) NOT NULL,
  `icon_link_url` VARCHAR(255) NOT NULL,
  `minimum_amount_created` INT UNSIGNED NOT NULL DEFAULT 1,
  `maximum_amount_created` INT UNSIGNED NOT NULL DEFAULT 1,
  `training_cost` INT UNSIGNED NULL,
  `recipe_item_id` INT UNSIGNED NULL,
  `craftable_item_id` INT UNSIGNED NULL,
  `profession_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_recipe_recipe_item1_idx` (`recipe_item_id` ASC),
  INDEX `fk_recipe_profession1_idx` (`profession_id` ASC),
  UNIQUE INDEX `recipe_link_url_UNIQUE` (`recipe_link_url` ASC),
  INDEX `fk_recipe_craftable_item1_idx` (`craftable_item_id` ASC),
  CONSTRAINT `fk_recipe_recipe_item1`
    FOREIGN KEY (`recipe_item_id`)
    REFERENCES `wow_classic_assistant`.`recipe_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recipe_profession1`
    FOREIGN KEY (`profession_id`)
    REFERENCES `wow_classic_assistant`.`profession` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recipe_craftable_item1`
    FOREIGN KEY (`craftable_item_id`)
    REFERENCES `wow_classic_assistant`.`craftable_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wow_classic_assistant`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wow_classic_assistant`.`location` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `location_link_url` VARCHAR(255) NOT NULL,
  `faction_status` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `location_link_url_UNIQUE` (`location_link_url` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wow_classic_assistant`.`trainer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wow_classic_assistant`.`trainer` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `trainer_link_url` VARCHAR(255) NOT NULL,
  `reaction_to_alliance` VARCHAR(255) NOT NULL DEFAULT 'Hostile',
  `reaction_to_horde` VARCHAR(255) NOT NULL DEFAULT 'Hostile',
  `location_id` INT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `trainer_link_url_UNIQUE` (`trainer_link_url` ASC),
  INDEX `fk_trainer_locations1_idx` (`location_id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  CONSTRAINT `fk_trainer_locations1`
    FOREIGN KEY (`location_id`)
    REFERENCES `wow_classic_assistant`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wow_classic_assistant`.`recipe_has_reagent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wow_classic_assistant`.`recipe_has_reagent` (
  `recipe_id` INT UNSIGNED NOT NULL,
  `reagent_id` INT UNSIGNED NOT NULL,
  `amount` INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`recipe_id`, `reagent_id`),
  INDEX `fk_recipe_has_ingredient_ingredient1_idx` (`reagent_id` ASC),
  INDEX `fk_recipe_has_ingredient_recipe1_idx` (`recipe_id` ASC),
  CONSTRAINT `fk_recipe_has_ingredient_recipe1`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `wow_classic_assistant`.`recipe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recipe_has_ingredient_ingredient1`
    FOREIGN KEY (`reagent_id`)
    REFERENCES `wow_classic_assistant`.`reagent` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wow_classic_assistant`.`character_has_profession`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wow_classic_assistant`.`character_has_profession` (
  `character_id` INT UNSIGNED NOT NULL,
  `profession_id` INT UNSIGNED NOT NULL,
  `current_skill_level` INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`character_id`, `profession_id`),
  INDEX `fk_character_has_profession_profession1_idx` (`profession_id` ASC),
  INDEX `fk_character_has_profession_character1_idx` (`character_id` ASC),
  CONSTRAINT `fk_character_has_profession_character1`
    FOREIGN KEY (`character_id`)
    REFERENCES `wow_classic_assistant`.`character` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_character_has_profession_profession1`
    FOREIGN KEY (`profession_id`)
    REFERENCES `wow_classic_assistant`.`profession` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wow_classic_assistant`.`recipe_has_trainer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wow_classic_assistant`.`recipe_has_trainer` (
  `recipe_id` INT UNSIGNED NOT NULL,
  `trainer_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`recipe_id`, `trainer_id`),
  INDEX `fk_recipe_has_trainer_trainer1_idx` (`trainer_id` ASC),
  INDEX `fk_recipe_has_trainer_recipe1_idx` (`recipe_id` ASC),
  CONSTRAINT `fk_recipe_has_trainer_recipe1`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `wow_classic_assistant`.`recipe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recipe_has_trainer_trainer1`
    FOREIGN KEY (`trainer_id`)
    REFERENCES `wow_classic_assistant`.`trainer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wow_classic_assistant`.`vendor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wow_classic_assistant`.`vendor` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `vendor_link_url` VARCHAR(255) NOT NULL,
  `reaction_to_alliance` VARCHAR(255) NOT NULL DEFAULT 'Hostile',
  `reaction_to_horde` VARCHAR(255) NOT NULL DEFAULT 'Hostile',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `vendor_link_url_UNIQUE` (`vendor_link_url` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wow_classic_assistant`.`reagent_has_vendor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wow_classic_assistant`.`reagent_has_vendor` (
  `reagent_id` INT UNSIGNED NOT NULL,
  `vendor_id` INT UNSIGNED NOT NULL,
  `buy_price` INT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`reagent_id`, `vendor_id`),
  INDEX `fk_reagents_has_vendors_vendors1_idx` (`vendor_id` ASC),
  INDEX `fk_reagents_has_vendors_reagents1_idx` (`reagent_id` ASC),
  CONSTRAINT `fk_reagents_has_vendors_reagents1`
    FOREIGN KEY (`reagent_id`)
    REFERENCES `wow_classic_assistant`.`reagent` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reagents_has_vendors_vendors1`
    FOREIGN KEY (`vendor_id`)
    REFERENCES `wow_classic_assistant`.`vendor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wow_classic_assistant`.`vendor_has_location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wow_classic_assistant`.`vendor_has_location` (
  `vendor_id` INT UNSIGNED NOT NULL,
  `location_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`vendor_id`, `location_id`),
  INDEX `fk_vendor_has_location_location1_idx` (`location_id` ASC),
  INDEX `fk_vendor_has_location_vendor1_idx` (`vendor_id` ASC),
  CONSTRAINT `fk_vendor_has_location_vendor1`
    FOREIGN KEY (`vendor_id`)
    REFERENCES `wow_classic_assistant`.`vendor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendor_has_location_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `wow_classic_assistant`.`location` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wow_classic_assistant`.`character_has_recipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wow_classic_assistant`.`character_has_recipe` (
  `character_id` INT UNSIGNED NOT NULL,
  `recipe_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`character_id`, `recipe_id`),
  INDEX `fk_character_has_recipe_recipe1_idx` (`recipe_id` ASC),
  INDEX `fk_character_has_recipe_character1_idx` (`character_id` ASC),
  CONSTRAINT `fk_character_has_recipe_character1`
    FOREIGN KEY (`character_id`)
    REFERENCES `wow_classic_assistant`.`character` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_character_has_recipe_recipe1`
    FOREIGN KEY (`recipe_id`)
    REFERENCES `wow_classic_assistant`.`recipe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wow_classic_assistant`.`source`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wow_classic_assistant`.`source` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wow_classic_assistant`.`reagent_has_source`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wow_classic_assistant`.`reagent_has_source` (
  `reagent_id` INT UNSIGNED NOT NULL,
  `source_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`reagent_id`, `source_id`),
  INDEX `fk_reagent_has_source_source1_idx` (`source_id` ASC),
  INDEX `fk_reagent_has_source_reagent1_idx` (`reagent_id` ASC),
  CONSTRAINT `fk_reagent_has_source_reagent1`
    FOREIGN KEY (`reagent_id`)
    REFERENCES `wow_classic_assistant`.`reagent` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reagent_has_source_source1`
    FOREIGN KEY (`source_id`)
    REFERENCES `wow_classic_assistant`.`source` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wow_classic_assistant`.`trainer_has_profession`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wow_classic_assistant`.`trainer_has_profession` (
  `trainer_id` INT UNSIGNED NOT NULL,
  `profession_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`trainer_id`, `profession_id`),
  INDEX `fk_trainer_has_profession_profession1_idx` (`profession_id` ASC),
  INDEX `fk_trainer_has_profession_trainer1_idx` (`trainer_id` ASC),
  CONSTRAINT `fk_trainer_has_profession_trainer1`
    FOREIGN KEY (`trainer_id`)
    REFERENCES `wow_classic_assistant`.`trainer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trainer_has_profession_profession1`
    FOREIGN KEY (`profession_id`)
    REFERENCES `wow_classic_assistant`.`profession` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
